  # SQL and document data store
  db:
    logging:
      driver: gcplogs
    image: postgres
    command:
      [
        '-c',
        'shared_buffers=1024MB',
        '-c',
        'max_connections=400',
        '-c',
        'effective_cache_size=1024MB',
      ]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - '0.0.0.0:5432:5432'

  pgbouncer:
    logging:
      driver: gcplogs
    image: brainsam/pgbouncer
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: docker
      DB_port: 5432
      DEFAULT_POOL_SIZE: 800
      MAX_CLIENT_CONN: 5000
      MAX_DB_CONNECTIONS: 380
      MAX_USER_CONNECTIONS: 380
    ports:
      - '0.0.0.0:6432:6432'

  # Distributed in-memory cache
  redis:
    logging:
      driver: gcplogs
    image: redis:4.0.6-alpine
    read_only: true
    volumes:
      - redis:/data
    user: redis

volumes:
  redis:
  yarn: