
// this file list of university for ranking the courses in the database
//=====================================================================


// Future Learn  raking data

export const FLUniversityList = {
  
  'University of Reading':	5,
  'Lancaster University':	5,
  'University of Birmingham':	10,
  'The University of Sheffield':	10,
  'University of Leicester':	5,
 'University of Southampton':	10,
  'The University of Edinburgh':	10,
  'University of Bath':	5,
  'University of Strathclyde':	5,
  "King's College London":	10,
  'UEA (University of East Anglia)':	5,
  'The University of Warwick':	10,
  'The Open University':	5,
  'The University of Nottingham':	5,
  'University of Glasgow':	10,
  'University of Leeds': 5,
  'British Council':	7,
  'Trinity College Dublin':	5,
  'Newcastle University':	5,
  'University of Liverpool':	5,
  'Monash University':	5,
  'The University of Auckland':	5,
  'University of Groningen':	10,
  'University of Bristol':	10,
  'UNSW Sydney':	10,
  'University of Exeter':	5,
  'University of Oslo':	5,
  'University of Dundee':	5,
  'National Film and Television School':	5,
  'London School of Hygiene & Tropical Medicine':	10,
  'University of Cape Town':	5,
  'University of Bergen':	5,
  'University of Twente':	5,
  'Tel Aviv University':	5,
  "St George's, University of London":	5,
  'University of Aberdeen':	5,
  'Hans Christian Andersen Centre':	5,
  'Pompeu Fabra University Barcelona':	5,
  'Shanghai International Studies University (SISU)':	5,
  'SOAS University of London':	5,
  'University of Basel':	10,
  'UNESCO UNITWIN Complex Systems Digital Campus':	7,
  'Sungkyunkwan University (SKKU)':	10,
  'UNSW Canberra':	5,
 'Universit√© Libre de Bruxelles':	5,
  'University of Wollongong':	5,
  'The British Film Institute (BFI)':	5,
  'Taipei Medical University':	10,
  'City University of Hong Kong':	5,
  'UCL (University College London)':	5,
  'Royal Holloway, University of London':	5,
  'The University of Manchester':	10,
  'Keio University':	5,
  'Eindhoven University of Technology':	5,
  'Queensland University of Technology':	5,
  'Cancer Research UK':	10,
  'Universit√† per Stranieri di Siena (UniStraSi)':	5,
  'Health Education England':	10,
  'Stellenbosch University':	5,
  'Weizmann Institute of Science':	10,
  'Cambridge Assessment English':	7,
  'Complutense University of Madrid':	5,
  'National STEM Learning Centre':	10,
  'Hanyang University':	5,
  'RMIT University':	5,
  'Goldsmiths, University of London':	5,
  'Durham University':	5,
  'EUMETSAT':	5,
  'Middlesex University Business School':	5,
  'Stockholm Environment Institute':	7,
  'Northumbria University Institute of the Humanities':	5,
  'National Tsing Hua University':	5,
  'The Hong Kong Academy for Performing Arts':	5,
  'The University of Waikato':	5,
  'University of York':	10,
  'International Confederation of Societies of Authors and Composers (CISAC)':	7,
  'University of Stellenbosch Business School Executive Development':	5,
  'Ambition School Leadership':	5,
  "√âcole Nationale de l'Aviation Civile":	10,
  'University of Malaya':	5,
  'Cardiff University':	5,
  'Partnership for Advanced Computing in Europe (PRACE)':	7,
  'Grenoble Ecole de Management':	5,
  'Deakin University':	5,
  'The University of Kent':	5,
  'International Federation of Red Cross and Red Crescent Societies (IFRC)':	7,
  'Raspberry Pi Foundation':	7,
  'Into Film':	5,
  'The Pennsylvania State University':	10,
  'University of California, Berkeley':	10,
  'Chartered Institute of Building Academy':	7,
  'The Graduate Institute of International and Development Studies':	7,
  'Purdue University':	10,
  'Manchester Metropolitan University':	5,
  'BSAC':	10,
  'Wellcome Genome Campus Advanced Courses and Scientific Conferences':	7,
  'European University Institute (EUI)':	5,
  'Darden School of Business, University of Virginia':	5,
  'Abertay University':	5,
  'Colorado State University':	5,
  'Kogod School of Business at American University':	5,
  'University of Padova':	5,
  'National Chiao Tung University':	5,
  'Humanists UK':	7,
  'Griffith University':	5,
  'Royal Observatory Greenwich':	7,
  'Macmillan Education':	7,
  'Norwegian University of Science and Technology (NTNU)':	5,
  'New York Institute of Finance':	5,
  'EIT InnoEnergy':	7,
  'Universit√† della Svizzera Italiana (USI)':	5,
  'Yad Vashem':	5,
  'Law Society of Scotland':	7,
  'Dublin City University':	5,
  "Film Distributors' Association":	7,
  'Murdoch University':	5,
  'The University of Melbourne':	10,
  'Coventry University':	5,
  'Accenture':	7,
  'Trinity Laban Conservatoire of Music and Dance':	5,
  'CIPD - Chartered Institute of Personnel and Development':	7,
  'Cambridge University Press':	7,
  'Universidad Nacional de C√≥rdoba':	5,
  'UNESCO':	7,
  'London College of Fashion':	5,
  'Association for Continence Advice':	5,
  'Swedish University of Agricultural Sciences (SLU)':	10,
  'Vrije Universiteit Amsterdam':	5,
  "The King's Fund":	5,
  'Emergency Planning College (EPC)':	7,
  'Aga Khan Trust for Culture':	5,
  'Johns Hopkins University':	10,
  'National Maritime Museum':	7,
  'Hanken School of Economics':	5,
  'ISAE-SUPAERO':	10,
  'Jindal Centre for Social Innovation + Entrepreneurship':	7,
  'EIT Food':	7,
  'British Heart Foundation':	10,
  'The University of Newcastle Australia':	5,
  "Girls' Day School Trust":	5,
  'Glion Institute of Higher Education':	5,
  'University of Roehampton':	5,
  'Anglia Ruskin University':	5,
  'EIT':	7,
  'NHS Leadership Academy':	10,
  'University of Oxford':	10,
  'Amnesty International':	7,
  'ABRSM':	7,
  'HKU School of Professional and Continuing Education':	10,
  'Chartered College of Teaching':	5,
  'Babcock Education':	7,
  'Fashion Revolution':	5,
  'Nankai University':	5,
  'Chartered Insurance Institute':	7,
  'Institut Fran√ßais de la mode (IFM)':	5,
  "BGI":	10,
  'Social Finance':	5,

}



// Future Learn Subject Mapping 
export const FLSubjectList = {

'Business & Management':	'B',
'Creative Arts & Media':	'A',
'Health & Psychology':	'HL',
'History':	'SO',
'Languages & Cultures':	'A',
'Law':	'SO',
'Psychology & Mental Health':'HL',
'Literature':	'A',
'Nature & Environment':	'SO',
'Politics & the Modern World':	'SO',
'Science, Engineering & Maths':	'SENG',
'Study Skills':	'O',
'Teaching':	'A',
'Language': 'SO',
'Politics & Society': 'SO',
'Healthcare & Medicine': 'HL',
'IT & Computer Science':	'CS' 
}




// edx raking data

export const EdxUniversityList = {
  "The University of Queensland" : 	10,                         
  "Delft University of Technology":	10,
  "The University of California, San Diego":	10,
"The University of Maryland, College Park, University System of Maryland":	5,
"Rochester Institute of Technology":	5,
"RWTH Aachen University":	5,
"Curtin University":	5,
"The World Wide Web Consortium (W3C)":	7,
"Chalmers University of Technology":	5,
"The Georgia Institute of Technology": 10,
"The University of Michigan, Microsoft In Education":	10,
"University of Pennsylvania":	10,
"UniversitâˆšÂ© catholique de Louvain":	5,
"Universitat PolitâˆšÂ®cnica de Valencia":	5,
"Inter-American Development Bank":	5,
"Indiana University":	5,
"The Wharton School of the University of Pennsylvania":	10,
"University System of Maryland, UMUC":	5,
"Davidson Next":	5,
"Massachusetts Institute of Technology":	10,
"The Hong Kong Polytechnic University":	10,
"IsraelX":	5,
"Wageningen University & Research":	10,
"Delft University of Technology, Wageningen University & Research, DelftWageningenX":	10,
"Indian Institute of Management Bangalore":	10,
"UMUC, University System of Maryland":	5,
"University of Adelaide":	5,
"The Hong Kong University of Science and Technology" :	10,
"Dartmouth College" :	5,
"The University of Michigan" :	10,
"Dartmouth College, IMT" :	5,
"World Bank Group" :	7,
"Wits University" :	5,
"Weston High School" :	5,
"Wellesley College" :	10,
"Waseda University" :	5,
"Victoria University of Wellington" :	5,
"Ural Federal University" :	5,
"University of Washington" :	10,
"University of Toronto	" :10,
"University of Maryland, Baltimore, University System of Maryland" :	5,
"University of Hong Kong" :	10,
"University of California, Berkeley" :	10,
"University of British Columbia" :	10,
"Universitâˆšâ€ degli Studi di Napoli Federico II" :	5,
"UniversitâˆšÂ© Mohammed VI Polytechnique" :	5,
"Universidad Nacional de Câˆšâ‰¥rdoba" :	5,
"Universidad Galileo" :	5,
"Universidad del Rosario":	5,
"Universidad Carlos III de Madrid":	5,
"Universidad Autâˆšâ‰¥noma de Madrid":	5,
"UMUC, University of Maryland, Baltimore, University System of Maryland":	5,
"Tsinghua University":	10,
"Tokyo Institute of Technology":	5,
"The University of Tokyo":	10,
"The University of Texas of the Permian Basin":	5,
"The University of Texas MD Anderson Cancer Center in Houston":	5,
"The University of Texas Health Science Center at Houston (UTHealth) School of Public Health":	5,
"The University of Texas at Austin":	10,
"The University of Queensland, Microsoft In Education":	5,
"The University of Newcastle, Australia":	5,
"The University of Maryland Eastern Shore, University System of Maryland":	5,
"The University of Iceland":	5,
"The University of Edinburgh":	5,
"The Smithsonian Institution":	5,
"The Linux Foundation":	7,
"The Islamic Research and Training Institute":	5,
"The International Monetary Fund":	7,
"TenarisUniversity":	5,
"Tecnolâˆšâ‰¥gico de Monterrey":	5,
"Technische UniversitâˆšÂ§t MâˆšÂºnchen":	5,
"Sorbonne UniversitâˆšÂ©":	5,
"seakademieX":	5,
"SDG Academy":	5,
"SchoolYourself":	5,
"Rice University":	5,
"Red Hat":	5,
"Purdue University":	10,
"Princeton University":	10,
"Pontificia Universidad Javeriana":	5,
"Perkins School for the Blind":	5,
"Peking University":	10,
"NYIF":	10,
"NUST MISIS":	5,
"New York University":	10,
"National Research Nuclear University":	10,
"MongoDB University":	7,
"Microsoft":	7,
"Massachusetts Institute of Technology, University of Pennsylvania":	10,
"MandarinX":	7,
"LOGYCA":	5,
"Kyoto University":	10,
"KU Leuven University":	5,
"KTH Royal Institute of Technology":	5,
"KIx: Karolinska Institutet":	5,
"ITMO University":	5,
"IMT" : 	5,
"Imperial College London, Imperial College Business School" : 	10,
"Imperial College London" : 	10,
"Imperial College Business School, Imperial College London" : 10,
"Imperial College Business School" : 	10,
"IITBombay" : 	10,
"IBM" : 	10,
"Harvard University" : 	10,
"Hamad Bin Khalifa University" : 	5,
"Georgetown University" : 	5,
"Fullbridge" : 	7,
"ETH Zurich" : 	10,
"edX" : 	7,
"Educational Testing Service" : 	7,
"Doane University" : 	5,
"Delft University of Technology, RWTH Aachen University, DelftXRWTHx" : 	7,
"Davidson College" : 	10,
"Cornell University, The University of Queensland, CornellX_UQx" : 	10,
"Cornell University" : 	10,
"Columbia University" : 	10,
"Catalyst" : 	7,
"Caltech" : 	10,
"Brown University" : 	10,
"Boston University":	10,
"Babson College":	5,
"Australian National University":	10,
"Arizona State University":	5,
"Amnesty International":	7,
"Amnesty International":	7,
"Amazon Web Services":	7,
"AfghanX":	5,
"ACCA":	7,
"âˆšÃ¢cole polytechnique fâˆšÂ©dâˆšÂ©rale de Lausanne":	5

}

export const EdxSubjectList = {
  "Business & Management":	'B',
'Computer Science': 	'CS',
'Humanitites' :	'A',
'Data Analysis & Statistics':	'DA',
'Language':	'SO',
'Architecture':	'SENG',
'Art & Culture':	'A',
'Biology & Life Sciences'	:'SENG',
'Chemistry':	'SENG',
'Communication' :	'SO',
'Design':	'A',
'Economics & Finance':	'B',
'Education & Teacher Training':	'A',
'Electronics':	'SENG',
'Energy & Earth Sciences': 	'SO',
'Engineering': 	'SENG',
'Environmental Studies':	'SO',
'Ethics':	'SO',
'Food & Nutrition': 	'HL',
'Health & Safety':	'HL',
'History':	'SO',
'Law':	'SO',
'Literature':	'A',
'Math':	'M',
'Medicine':	'HL',
'Music':	'A',
'Philanthropy':	'O',
'Philosophy & Ethics':	'O',
'Physics':	'SENG',
'Science':	'SENG',
'Social Sciences': 	'SO'

}


// coursera raking data 

export const CourseraUniversityList = {
    "Yale University" :	10,
    "Universitat de Barcelona ":	5,
    "Duke University"	: 10,
    "Sciences Po" :	7,
    "University of Virginia" :	5,
    "University of Pennsylvania" :	10,
    "Universidad de Chile" :	5,
    "Politecnico di Milano" :	5,
    "Sapienza University of Rome":	5,
    "University of Amsterdam" :	10,
    "Macquarie University" :	5,
    "Nanjing University" :	5,
    "University of Colorado System" :	5,
    "The University of Sydney" :	5,
    "National Research University Higher School of Economics" :	5,
    "Universitat Autònoma de Barcelona":	5,
    "The Museum of Modern Art" :	7,
    "University of London" :	5,
    "Universidad de los Andes":	5,
    "Yonsei University":	5,
    "University of Geneva":	5,
    "University of Florida":	5,
    "University of Rochester":	5,
    "California Institute of the Arts":	5,
    "University of Alberta":	5,
    "Ludwig-Maximilians-Universität München LMU":	10,
    "Universiteit Leiden":	5,
    "University of Arizona":	5,
    "University of California, Santa Cruz":	10,
    "University of Copenhagen":	10,
    "Wesleyan University":	5,
    "Emory University":	5,
    "Tel Aviv University":	5,
    "Tel Aviv University & Yad Vashem":	5,
    "Northwestern University":	10,
    "Stanford University":	10,
    "The University of Tokyo":	10,
    "Saint Petersburg State University":	5,
    "National Taiwan University":	5,
    "University of New Mexico":	5,
    "IE Business School":	10,
    "University of Colorado Boulder":	10,
    "National Research Tomsk State University":	5,
    "Michigan State University":	5,
    "Berklee College of Music" :	5,
    "Universidad Nacional Autónoma de México":	5,
    "Curtis Institute of Music":	5,
    "The University of Edinburgh":	10,
    "University of California, Irvine":	10,
    "High Tech High Graduate School of Education":	5,
    "The University of Melbourne":	5,
    "University of Maryland, College Park":	5,
    "National University of Singapore":	10,
    "Novosibirsk State University":	5,
    "University of Lausanne":	5,
    "Nanyang Technological University, Singapore":	10,
    "ESSEC Business School":	10,
    "Korea Advanced Institute of Science and TechnologyKAIST" : 	5,
    "Erasmus University Rotterdam":	5,
    "Hebrew University of Jerusalem":	5,
    "The University of North Carolina at Chapel Hill":	5,
    "Rutgers the State University of New Jersey":	5,
    "Fudan University":	5,
    "Xi'an Jiaotong University" :	5,
    "Peking University":	10,
    "UNSW Sydney The University of New South Wales":	5,
    "Utrecht University":	5,
    "E-Learning Development Fund & National Research Tomsk State University":	5,
    "Arizona State University":	5,
    "University of Washington":	10,
    "The Hong Kong University of Science and Technology":	5,
    "Rice University":	10,
    "PwC":	7,
    "University of California, Davis":	10,
    "Johns Hopkins University":	10,
    "University of Illinois at Urbana-Champaign":	10,
    "Georgia Institute of Technolog":10,
    "University System of Georgia":	5,
    "IESE Business School":	10,
    "Pontificia Universidad Católica de Chile":	5,
    "University of Michigan":	5,
    "University of Minnesota":	5,
    "INSEAD":	10,
    "Google Cloud":	7,
    "Tecnológico de Monterrey":	5,
    "Copenhagen Business School":	10,
    "Brightline Initiative":	7,
    "Universidade Estadual de Campinas":	5,
    "Columbia University":	10,
    "Università Bocconi":	5,
    "Lund University":	10,
    "Insper":	5,
    "Indian School of Business":	10,
    "Universidade de São Paulo":	5,
    "deeplearning.ai":	7,
    "The Chinese University of Hong Kong":	5,
    "Technion - Israel Institute of Technology":	10,
    "EIT Digital":	7,
    "HEC Paris":	5,
    "University of Cape Town":	5,
    "HEC Paris & École Polytechnique":	5,
    "emlyon business school":	5,
    "Vanderbilt University":	5,
    "Moscow Institute of Physics and Technology":	5,
    "Universidad Austral":	5,
    "Goldman Sachs":	7,
    "McMaster University":	5,
    "West Virginia University":	5,
    "Sberbank Corporate University":	5,
    "Google Cloud & New York Institute of Finance":	7,
    "EDHEC Business School":	10,
    "Tecnológico de Monterrey & University of California, Irvine":	5,
    'Case Western Reserve University':	5,
    'University of Toronto':	10,
    'University of California San Diego':	10,
    'BCG & University of Virginia':	7,
    'Fundação Instituto de Administração':	5,
    'HubSpot Academy':	7,
    'The State University of New York':	5,
    'Peter the Great St. Petersburg Polytechnic University':	5,
    'Princeton University':	10,
    'École Polytechnique Fédérale de Lausanne':	5,
    'SAS':	7,
    'IBM':	7,
    'Alberta Machine Intelligence Institute & University of Alberta':	5,
    'New York University Tandon School of Engineering':	10,
    'The University of Chicago':	10,
    'Autodesk':	7,
    'Unity':	7,
    'Google AR & VR':	7,
    'E-Learning Development Fund':7,
    'CentraleSupélec':	5,
    'Imperial College London':	10,
    'LearnQuest':	7,
    'Duke University & University of California San Diego':	10,
    'JetBrains':	7,
    'Atlassian':	7,
    'Amazon Web Services':	7,
    'MathWorks':	7,
    'University of Zurich':	10,
    'Eindhoven University of Technology':	10,
    'The Pennsylvania State University':	10,
    'Technical University of Denmark DTU':	5,
    'University of Western Australia':	5,
    'erican Museum of Natural History':	7,
    'University of California San Diego & University of Colorado Boulder':	10,
    'Icahn School of Medicine at Mount Sinai':	5,
    'The University of Hong Kong':	10,
    'Copenhagen Business School & Technical University of Denmark DTU':	10,
    'Johns Hopkins University & University of Colorado Boulder'	:10,
    'Northeastern University':	5,
    'University of Glasgow':	5,
    'Copenhagen Business School & University of Copenhagen':	10,
    'The George Washington University':	5,
    'Technische Universität München TUM':	5,
    'Koç University':	5,
    'Shanghai Jiao Tong University':	5,
    'University of Amsterdam & Utrecht University':	5,
    'University of Pittsburgh':	5,
    'University of Houston System':	5,
    'National Research Nuclear University MEPhI':	7,
    'University of Geneva & University of Lausanne':	5,
    'University of Manchester':	10,
    'Google':	7,
    'MongoDB Inc.':	7,
    'Cloudera':	7,
    'Alberta Machine Intelligence Institute':	7,
    'Association of International Certified Professional Accountants':	7,
    'Automation Anywhere':	7,
    'Cisco':	7,
    'Intel':	7,
    'VMware':	7,
    'Pohang University of Science and Technology':	5,
    'Google - Spectrum Sharing':	7,
    'Cresça com o Google':	7,
    'Crece con Google':	7,
    'Palo Alto Networks':	7,
    'ISC²':	7,
    'ConsenSys Academy':	7,
    'Commonwealth Education Trust':	7,
    'Tsinghua University':	10,
    'École Polytechnique':	5,
    'The Chinese University of Hong Kong & The University of Melbourne':	5,
    'McMaster University & University of California San Diego':	5,
    'École des Ponts ParisTech':	5,
    'Duke University & The University of North Carolina at Chapel Hill':	10,
    'Carnegie Mellon University':	10,
    'Instituto Tecnológico de Aeronáutica':	5,
    'Institut Mines-Télécom':	5,
    'EIT RawMaterials & Lund University':	5,
    'ESCP Business School':	5,
    'University of Leeds':	5,
    'Exploratorium':7,
    'University of Arizona & University of Florida':	5,
    'École normale supérieure':	5,
    'Caltech':	1,
    
    'ESADE Business and Law School':	1,
    
    'Arizona State University & Universidad Nacional Autónoma de México':	5,
    'New Teacher Center & Relay Graduate School of Education':	5,
    'Fundação Lemann':	5,
    'Relay Graduate School of Education':	5,
    'The State University of New York & The University of Hong Kong':	1,
    
    "Universidade de São Paulo & University of California, Irvine":	5,
    "University of Maryland, College Park & University of Michigan":	5,
    'University of Science and Technology of China':	5,
    'Technical University of Denmark DTU & University of Copenhagen':	1,
    
    'Yeshiva University':	5,
    'The World Bank Group':	7,
    'Yandex':	7,
    'University of Nebraska':	5,
    'H2O':	7,
    'BCG & École des Ponts ParisTech':	7,
    'The Linux Foundation':	7,
    'Match Teacher Residency':	5,
    'New York Institute of Finance':	10,
    'EIT Digital & Politecnico di Milano':	5,
    'Yad Vashem':	5,
    'Alibaba Cloud Academy':	7
    
      }
       